### ISSUE TITLE
Any example using detection, segmentation

### ISSUE THREAD

**Issue by Ashutosh1995** [JJGO/hyperlight#2]
Hi,

Thanks for open-sourcing this repository!

My doubt is how to use the current repo if I want to train a normal segmentation network using hypernetwork. It would be great if 
you could provide some pointers.

Also, when running the following command,

hypernet = hl.Hypernet(
    input_shapes=hyperparam_shape,
    output_shapes=parameter_shapes,
    hidden_sizes=[16,64,128],
)

I get the following error: 
![Screenshot from 2023-05-18 22-28-53](https://github.com/JJGO/hyperlight/assets/11408850/56e1b5d5-2317-4075-ab69-dbe4f351ac99)

Kindly help in this regard!

**Comment by JJGO** [comment]
Hey

There was a typo in the docs (Hypernet -> HyperNet). I've updated them and it should work now. You can also read them as an interactive colab [here](https://colab.research.google.com/drive/1Ejo4a_FDP4Gay2U93uxbKa48HyeuxrL4?usp=sharing).

For a segmentation network, I'd suggest defining a regular U-Net model using pytorch and then using hyperlight to hypernetize the layers you want. The tutorial should be a good intro on how to do this.
